global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'danube-brokers'
    static_configs:
      - targets:
          - 'host.docker.internal:9040'
          - 'host.docker.internal:9041'
          - 'host.docker.internal:9042'
